 enum LinkState {
    DISCONNECTED  = "DISCONNECTED",
    CONNECTING    = "CONNECTING",
    CONNECTED     = "CONNECTED",
    DISCONNECTING = "DISCONNECTING",
    LINKDOWN      = "LINKDOWN",
    RECONNECTING  = "RECONNECTING",
}

 export default LinkState;
